/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.doscom.TeaLinuxInstaller.view;

import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author zword
 */
public class DisplayPanel extends javax.swing.JPanel {
    /**
     * Creates new form DisplayPanel
     */
    public DisplayPanel() {
        initComponents();
        buttonImage1.setImage(new ImageIcon(getClass().getResource("/com/doscom/TeaLinuxInstaller/picture/KukichaDesk.png")).getImage());
    }
    
    public void changeImage(Image image){
        buttonImage1.setImage(image);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonImage1 = new com.doscom.TeaLinuxInstaller.template.ButtonImage();

        setPreferredSize(new java.awt.Dimension(400, 230));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(buttonImage1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(buttonImage1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.doscom.TeaLinuxInstaller.template.ButtonImage buttonImage1;
    // End of variables declaration//GEN-END:variables
}
