/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.doscom.TeaLinuxInstaller.view;

import javax.swing.ImageIcon;

/**
 *
 * @author zword
 */
public class DisplayPanel extends javax.swing.JInternalFrame {

    /**
     * Creates new form DisplayPanel
     */
    public DisplayPanel(String Ide) {
        initComponents();
        
        displaySelc(Ide);
        
        this.setRootPaneCheckingEnabled(false);
        javax.swing.plaf.InternalFrameUI ifu= this.getUI();
        ((javax.swing.plaf.basic.BasicInternalFrameUI)ifu).setNorthPane(null);

    }
    
    private void displaySelc(String Ide){
        if(Ide == "init")
            buttonImage1.setImage(new ImageIcon(getClass().getResource("/com/doscom/TeaLinuxInstaller/picture/KukichaDesk.png")).getImage());

    } 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonImage1 = new com.doscom.TeaLinuxInstaller.template.ButtonImage();

        setPreferredSize(new java.awt.Dimension(406, 243));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(buttonImage1, javax.swing.GroupLayout.DEFAULT_SIZE, 396, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(buttonImage1, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.doscom.TeaLinuxInstaller.template.ButtonImage buttonImage1;
    // End of variables declaration//GEN-END:variables
}
